// import "./theme/custom.css";

export default {
  title: "Opcode Explained",
  description: "Documenting bitcoin opcodes",
  themeConfig: {
    search: {
      provider: "local"
    },

    nav: [
      { text: "Opcodes", link: "/opcodes/", activeMatch: "/opcodes/" },
      { text: "Script", link: "/script/", activeMatch: "/script/" }
    ],

    sidebar: {
      "/opcodes/": [
        { text: "<code>0 | OP_0</code>", link: "/opcodes/OP_0.md" },
        { text: "<code>1 | OP_PUSHBYTES_1</code>", link: "/opcodes/OP_PUSHBYTES_1.md" },
        { text: "<code>2 | OP_PUSHBYTES_2</code>", link: "/opcodes/OP_PUSHBYTES_2.md" },
        { text: "<code>3 | OP_PUSHBYTES_3</code>", link: "/opcodes/OP_PUSHBYTES_3.md" },
        { text: "<code>4 | OP_PUSHBYTES_4</code>", link: "/opcodes/OP_PUSHBYTES_4.md" },
        { text: "<code>5 | OP_PUSHBYTES_5</code>", link: "/opcodes/OP_PUSHBYTES_5.md" },
        { text: "<code>6 | OP_PUSHBYTES_6</code>", link: "/opcodes/OP_PUSHBYTES_6.md" },
        { text: "<code>7 | OP_PUSHBYTES_7</code>", link: "/opcodes/OP_PUSHBYTES_7.md" },
        { text: "<code>8 | OP_PUSHBYTES_8</code>", link: "/opcodes/OP_PUSHBYTES_8.md" },
        { text: "<code>9 | OP_PUSHBYTES_9</code>", link: "/opcodes/OP_PUSHBYTES_9.md" },
        { text: "<code>10 | OP_PUSHBYTES_10</code>", link: "/opcodes/OP_PUSHBYTES_10.md" },
        { text: "<code>11 | OP_PUSHBYTES_11</code>", link: "/opcodes/OP_PUSHBYTES_11.md" },
        { text: "<code>12 | OP_PUSHBYTES_12</code>", link: "/opcodes/OP_PUSHBYTES_12.md" },
        { text: "<code>13 | OP_PUSHBYTES_13</code>", link: "/opcodes/OP_PUSHBYTES_13.md" },
        { text: "<code>14 | OP_PUSHBYTES_14</code>", link: "/opcodes/OP_PUSHBYTES_14.md" },
        { text: "<code>15 | OP_PUSHBYTES_15</code>", link: "/opcodes/OP_PUSHBYTES_15.md" },
        { text: "<code>16 | OP_PUSHBYTES_16</code>", link: "/opcodes/OP_PUSHBYTES_16.md" },
        { text: "<code>17 | OP_PUSHBYTES_17</code>", link: "/opcodes/OP_PUSHBYTES_17.md" },
        { text: "<code>18 | OP_PUSHBYTES_18</code>", link: "/opcodes/OP_PUSHBYTES_18.md" },
        { text: "<code>19 | OP_PUSHBYTES_19</code>", link: "/opcodes/OP_PUSHBYTES_19.md" },
        { text: "<code>20 | OP_PUSHBYTES_20</code>", link: "/opcodes/OP_PUSHBYTES_20.md" },
        { text: "<code>21 | OP_PUSHBYTES_21</code>", link: "/opcodes/OP_PUSHBYTES_21.md" },
        { text: "<code>22 | OP_PUSHBYTES_22</code>", link: "/opcodes/OP_PUSHBYTES_22.md" },
        { text: "<code>23 | OP_PUSHBYTES_23</code>", link: "/opcodes/OP_PUSHBYTES_23.md" },
        { text: "<code>24 | OP_PUSHBYTES_24</code>", link: "/opcodes/OP_PUSHBYTES_24.md" },
        { text: "<code>25 | OP_PUSHBYTES_25</code>", link: "/opcodes/OP_PUSHBYTES_25.md" },
        { text: "<code>26 | OP_PUSHBYTES_26</code>", link: "/opcodes/OP_PUSHBYTES_26.md" },
        { text: "<code>27 | OP_PUSHBYTES_27</code>", link: "/opcodes/OP_PUSHBYTES_27.md" },
        { text: "<code>28 | OP_PUSHBYTES_28</code>", link: "/opcodes/OP_PUSHBYTES_28.md" },
        { text: "<code>29 | OP_PUSHBYTES_29</code>", link: "/opcodes/OP_PUSHBYTES_29.md" },
        { text: "<code>30 | OP_PUSHBYTES_30</code>", link: "/opcodes/OP_PUSHBYTES_30.md" },
        { text: "<code>31 | OP_PUSHBYTES_31</code>", link: "/opcodes/OP_PUSHBYTES_31.md" },
        { text: "<code>32 | OP_PUSHBYTES_32</code>", link: "/opcodes/OP_PUSHBYTES_32.md" },
        { text: "<code>33 | OP_PUSHBYTES_33</code>", link: "/opcodes/OP_PUSHBYTES_33.md" },
        { text: "<code>34 | OP_PUSHBYTES_34</code>", link: "/opcodes/OP_PUSHBYTES_34.md" },
        { text: "<code>35 | OP_PUSHBYTES_35</code>", link: "/opcodes/OP_PUSHBYTES_35.md" },
        { text: "<code>36 | OP_PUSHBYTES_36</code>", link: "/opcodes/OP_PUSHBYTES_36.md" },
        { text: "<code>37 | OP_PUSHBYTES_37</code>", link: "/opcodes/OP_PUSHBYTES_37.md" },
        { text: "<code>38 | OP_PUSHBYTES_38</code>", link: "/opcodes/OP_PUSHBYTES_38.md" },
        { text: "<code>39 | OP_PUSHBYTES_39</code>", link: "/opcodes/OP_PUSHBYTES_39.md" },
        { text: "<code>40 | OP_PUSHBYTES_40</code>", link: "/opcodes/OP_PUSHBYTES_40.md" },
        { text: "<code>41 | OP_PUSHBYTES_41</code>", link: "/opcodes/OP_PUSHBYTES_41.md" },
        { text: "<code>42 | OP_PUSHBYTES_42</code>", link: "/opcodes/OP_PUSHBYTES_42.md" },
        { text: "<code>43 | OP_PUSHBYTES_43</code>", link: "/opcodes/OP_PUSHBYTES_43.md" },
        { text: "<code>44 | OP_PUSHBYTES_44</code>", link: "/opcodes/OP_PUSHBYTES_44.md" },
        { text: "<code>45 | OP_PUSHBYTES_45</code>", link: "/opcodes/OP_PUSHBYTES_45.md" },
        { text: "<code>46 | OP_PUSHBYTES_46</code>", link: "/opcodes/OP_PUSHBYTES_46.md" },
        { text: "<code>47 | OP_PUSHBYTES_47</code>", link: "/opcodes/OP_PUSHBYTES_47.md" },
        { text: "<code>48 | OP_PUSHBYTES_48</code>", link: "/opcodes/OP_PUSHBYTES_48.md" },
        { text: "<code>49 | OP_PUSHBYTES_49</code>", link: "/opcodes/OP_PUSHBYTES_49.md" },
        { text: "<code>50 | OP_PUSHBYTES_50</code>", link: "/opcodes/OP_PUSHBYTES_50.md" },
        { text: "<code>51 | OP_PUSHBYTES_51</code>", link: "/opcodes/OP_PUSHBYTES_51.md" },
        { text: "<code>52 | OP_PUSHBYTES_52</code>", link: "/opcodes/OP_PUSHBYTES_52.md" },
        { text: "<code>53 | OP_PUSHBYTES_53</code>", link: "/opcodes/OP_PUSHBYTES_53.md" },
        { text: "<code>54 | OP_PUSHBYTES_54</code>", link: "/opcodes/OP_PUSHBYTES_54.md" },
        { text: "<code>55 | OP_PUSHBYTES_55</code>", link: "/opcodes/OP_PUSHBYTES_55.md" },
        { text: "<code>56 | OP_PUSHBYTES_56</code>", link: "/opcodes/OP_PUSHBYTES_56.md" },
        { text: "<code>57 | OP_PUSHBYTES_57</code>", link: "/opcodes/OP_PUSHBYTES_57.md" },
        { text: "<code>58 | OP_PUSHBYTES_58</code>", link: "/opcodes/OP_PUSHBYTES_58.md" },
        { text: "<code>59 | OP_PUSHBYTES_59</code>", link: "/opcodes/OP_PUSHBYTES_59.md" },
        { text: "<code>60 | OP_PUSHBYTES_60</code>", link: "/opcodes/OP_PUSHBYTES_60.md" },
        { text: "<code>61 | OP_PUSHBYTES_61</code>", link: "/opcodes/OP_PUSHBYTES_61.md" },
        { text: "<code>62 | OP_PUSHBYTES_62</code>", link: "/opcodes/OP_PUSHBYTES_62.md" },
        { text: "<code>63 | OP_PUSHBYTES_63</code>", link: "/opcodes/OP_PUSHBYTES_63.md" },
        { text: "<code>64 | OP_PUSHBYTES_64</code>", link: "/opcodes/OP_PUSHBYTES_64.md" },
        { text: "<code>65 | OP_PUSHBYTES_65</code>", link: "/opcodes/OP_PUSHBYTES_65.md" },
        { text: "<code>66 | OP_PUSHBYTES_66</code>", link: "/opcodes/OP_PUSHBYTES_66.md" },
        { text: "<code>67 | OP_PUSHBYTES_67</code>", link: "/opcodes/OP_PUSHBYTES_67.md" },
        { text: "<code>68 | OP_PUSHBYTES_68</code>", link: "/opcodes/OP_PUSHBYTES_68.md" },
        { text: "<code>69 | OP_PUSHBYTES_69</code>", link: "/opcodes/OP_PUSHBYTES_69.md" },
        { text: "<code>70 | OP_PUSHBYTES_70</code>", link: "/opcodes/OP_PUSHBYTES_70.md" },
        { text: "<code>71 | OP_PUSHBYTES_71</code>", link: "/opcodes/OP_PUSHBYTES_71.md" },
        { text: "<code>72 | OP_PUSHBYTES_72</code>", link: "/opcodes/OP_PUSHBYTES_72.md" },
        { text: "<code>73 | OP_PUSHBYTES_73</code>", link: "/opcodes/OP_PUSHBYTES_73.md" },
        { text: "<code>74 | OP_PUSHBYTES_74</code>", link: "/opcodes/OP_PUSHBYTES_74.md" },
        { text: "<code>75 | OP_PUSHBYTES_75</code>", link: "/opcodes/OP_PUSHBYTES_75.md" },
        { text: "<code>76 | OP_PUSHDATA1</code>", link: "/opcodes/OP_PUSHDATA1.md" },
        { text: "<code>77 | OP_PUSHDATA2</code>", link: "/opcodes/OP_PUSHDATA2.md" },
        { text: "<code>78 | OP_PUSHDATA4</code>", link: "/opcodes/OP_PUSHDATA4.md" },
        { text: "<code>79 | OP_1NEGATE</code>", link: "/opcodes/OP_1NEGATE.md" },
        { text: "<code>80 | OP_RESERVED</code>", link: "/opcodes/OP_RESERVED.md" },
        { text: "<code>81 | OP_1</code>", link: "/opcodes/OP_1.md" },
        { text: "<code>82 | OP_2</code>", link: "/opcodes/OP_2.md" },
        { text: "<code>83 | OP_3</code>", link: "/opcodes/OP_3.md" },
        { text: "<code>84 | OP_4</code>", link: "/opcodes/OP_4.md" },
        { text: "<code>85 | OP_5</code>", link: "/opcodes/OP_5.md" },
        { text: "<code>86 | OP_6</code>", link: "/opcodes/OP_6.md" },
        { text: "<code>87 | OP_7</code>", link: "/opcodes/OP_7.md" },
        { text: "<code>88 | OP_8</code>", link: "/opcodes/OP_8.md" },
        { text: "<code>89 | OP_9</code>", link: "/opcodes/OP_9.md" },
        { text: "<code>90 | OP_10</code>", link: "/opcodes/OP_10.md" },
        { text: "<code>91 | OP_11</code>", link: "/opcodes/OP_11.md" },
        { text: "<code>92 | OP_12</code>", link: "/opcodes/OP_12.md" },
        { text: "<code>93 | OP_13</code>", link: "/opcodes/OP_13.md" },
        { text: "<code>94 | OP_14</code>", link: "/opcodes/OP_14.md" },
        { text: "<code>95 | OP_15</code>", link: "/opcodes/OP_15.md" },
        { text: "<code>96 | OP_16</code>", link: "/opcodes/OP_16.md" },
        { text: "<code>97 | OP_NOP</code>", link: "/opcodes/OP_NOP.md" },
        { text: "<code>98 | OP_VER</code>", link: "/opcodes/OP_VER.md" },
        { text: "<code>99 | OP_IF</code>", link: "/opcodes/OP_IF.md" },
        { text: "<code>100 | OP_NOTIF</code>", link: "/opcodes/OP_NOTIF.md" },
        { text: "<code>101 | OP_VERIF</code>", link: "/opcodes/OP_VERIF.md" },
        { text: "<code>102 | OP_VERNOTIF</code>", link: "/opcodes/OP_VERNOTIF.md" },
        { text: "<code>103 | OP_ELSE</code>", link: "/opcodes/OP_ELSE.md" },
        { text: "<code>104 | OP_ENDIF</code>", link: "/opcodes/OP_ENDIF.md" },
        { text: "<code>105 | OP_VERIFY</code>", link: "/opcodes/OP_VERIFY.md" },
        { text: "<code>106 | OP_RETURN</code>", link: "/opcodes/OP_RETURN.md" },
        { text: "<code>107 | OP_TOALTSTACK</code>", link: "/opcodes/OP_TOALTSTACK.md" },
        { text: "<code>108 | OP_FROMALTSTACK</code>", link: "/opcodes/OP_FROMALTSTACK.md" },        
        { text: "<code>109 | OP_2DROP</code>", link: "/opcodes/OP_2DROP.md" },
        { text: "<code>110 | OP_2DUP</code>", link: "/opcodes/OP_2DUP.md" },
        { text: "<code>111 | OP_3DUP</code>", link: "/opcodes/OP_3DUP.md" },
        { text: "<code>112 | OP_2OVER</code>", link: "/opcodes/OP_2OVER.md" },
        { text: "<code>113 | OP_2ROT</code>", link: "/opcodes/OP_2ROT.md" },
        { text: "<code>114 | OP_2SWAP</code>", link: "/opcodes/OP_2SWAP.md" },
        { text: "<code>115 | OP_IFDUP</code>", link: "/opcodes/OP_IFDUP.md" },
        { text: "<code>116 | OP_DEPTH</code>", link: "/opcodes/OP_DEPTH.md" },
        { text: "<code>117 | OP_DROP</code>", link: "/opcodes/WIP.md" },
        { text: "<code>118 | OP_DUP</code>", link: "/opcodes/WIP.md" },
        { text: "<code>119 | OP_NIP</code>", link: "/opcodes/WIP.md" },
        { text: "<code>120 | OP_OVER</code>", link: "/opcodes/OP_OVER.md" },
        { text: "<code>121 | OP_PICK</code>", link: "/opcodes/WIP.md" },
        { text: "<code>122 | OP_ROLL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>123 | 🚧 OP_ROT</code>", link: "/opcodes/WIP.md" },
        { text: "<code>124 | 🚧 OP_SWAP</code>", link: "/opcodes/WIP.md" },
        { text: "<code>125 | 🚧 OP_TUCK</code>", link: "/opcodes/WIP.md" },
        { text: "<code>126 | OP_CAT</code>", link: "/opcodes/OP_CAT.md" },
        { text: "<code>127 | OP_SUBSTR</code>", link: "/opcodes/OP_SUBSTR.md" },
        { text: "<code>128 | OP_LEFT</code>", link: "/opcodes/OP_LEFT.md" },
        { text: "<code>129 | OP_RIGHT</code>", link: "/opcodes/OP_RIGHT.md" },
        { text: "<code>130 | OP_SIZE</code>", link: "/opcodes/OP_SIZE.md" },
        { text: "<code>131 | OP_INVERT</code>", link: "/opcodes/OP_INVERT.md" },
        { text: "<code>132 | OP_AND</code>", link: "/opcodes/OP_AND.md" },
        { text: "<code>133 | OP_OR</code>", link: "/opcodes/OP_OR.md" },
        { text: "<code>134 | OP_XOR</code>", link: "/opcodes/OP_XOR.md" },
        { text: "<code>135 | 🚧 OP_EQUAL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>136 | 🚧 OP_EQUALVERIFY</code>", link: "/opcodes/WIP.md" },
        { text: "<code>137 | 🚧 OP_RESERVED1</code>", link: "/opcodes/WIP.md" },
        { text: "<code>138 | 🚧 OP_RESERVED2</code>", link: "/opcodes/WIP.md" },
        { text: "<code>139 | 🚧 OP_1ADD</code>", link: "/opcodes/WIP.md" },
        { text: "<code>140 | 🚧 OP_1SUB</code>", link: "/opcodes/WIP.md" },
        { text: "<code>141 | OP_2MUL</code>", link: "/opcodes/OP_2MUL.md" },
        { text: "<code>142 | OP_2DIV</code>", link: "/opcodes/OP_2DIV.md" },
        { text: "<code>143 | 🚧 OP_NEGATE</code>", link: "/opcodes/WIP.md" },
        { text: "<code>144 | 🚧 OP_ABS</code>", link: "/opcodes/WIP.md" },
        { text: "<code>145 | 🚧 OP_NOT</code>", link: "/opcodes/WIP.md" },
        { text: "<code>146 | 🚧 OP_0NOTEQUAL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>147 | OP_ADD</code>", link: "/opcodes/OP_ADD.md" },
        { text: "<code>149 | OP_MUL</code>", link: "/opcodes/OP_MUL.md" },
        { text: "<code>148 | 🚧 OP_SUB</code>", link: "/opcodes/WIP.md" },
        { text: "<code>150 | OP_DIV</code>", link: "/opcodes/OP_DIV.md" },
        { text: "<code>151 | OP_MOD</code>", link: "/opcodes/OP_MOD.md" },
        { text: "<code>152 | OP_LSHIFT</code>", link: "/opcodes/OP_LSHIFT.md" },
        { text: "<code>153 | OP_RSHIFT</code>", link: "/opcodes/OP_RSHIFT.md" },
        { text: "<code>154 | 🚧 OP_BOOLAND</code>", link: "/opcodes/WIP.md" },
        { text: "<code>155 | 🚧 OP_BOOLOR</code>", link: "/opcodes/WIP.md" },
        { text: "<code>156 | 🚧 OP_NUMEQUAL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>157 | 🚧 OP_NUMEQUALVERIFY</code>", link: "/opcodes/WIP.md" },
        { text: "<code>158 | 🚧 OP_NUMNOTEQUAL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>159 | 🚧 OP_LESSTHAN</code>", link: "/opcodes/WIP.md" },
        { text: "<code>160 | 🚧 OP_GREATERTHAN</code>", link: "/opcodes/WIP.md" },
        { text: "<code>161 | 🚧 OP_LESSTHANOREQUAL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>162 | 🚧 OP_GREATERTHANOREQUAL</code>", link: "/opcodes/WIP.md" },
        { text: "<code>163 | 🚧 OP_MIN</code>", link: "/opcodes/WIP.md" },
        { text: "<code>164 | 🚧 OP_MAX</code>", link: "/opcodes/WIP.md" },
        { text: "<code>165 | 🚧 OP_WITHIN</code>", link: "/opcodes/WIP.md" },
        { text: "<code>166 | OP_RIPEMD160</code>", link: "/opcodes/OP_RIPEMD160.md" },
        { text: "<code>167 | OP_SHA1</code>", link: "/opcodes/OP_SHA1.md" },
        { text: "<code>168 | OP_SHA256</code>", link: "/opcodes/OP_SHA256.md" },
        { text: "<code>169 | OP_HASH160</code>", link: "/opcodes/OP_HASH160.md" },
        { text: "<code>170 | OP_HASH256</code>", link: "/opcodes/OP_HASH256.md" },
        { text: "<code>171 | 🚧 OP_CODESEPARATOR</code>", link: "/opcodes/WIP.md" },
        { text: "<code>172 | 🚧 OP_CHECKSIG</code>", link: "/opcodes/WIP.md" },
        { text: "<code>173 | 🚧 OP_CHECKSIGVERIFY</code>", link: "/opcodes/WIP.md" },
        { text: "<code>174 | 🚧 OP_CHECKMULTISIG</code>", link: "/opcodes/WIP.md" },
        { text: "<code>175 | 🚧 OP_CHECKMULTISIGVERIFY</code>", link: "/opcodes/WIP.md" },
        { text: "<code>176 | OP_NOP1</code>", link: "/opcodes/OP_NOP1.md" },
        { text: "<code>177 | 🚧 OP_CLTV</code>", link: "/opcodes/WIP.md" },
        { text: "<code>178 | 🚧 OP_CSV</code>", link: "/opcodes/WIP.md" },
        { text: "<code>179 | OP_NOP4</code>", link: "/opcodes/OP_NOP4.md" },
        { text: "<code>180 | OP_NOP5</code>", link: "/opcodes/OP_NOP5.md" },
        { text: "<code>181 | OP_NOP6</code>", link: "/opcodes/OP_NOP6.md" },
        { text: "<code>182 | OP_NOP7</code>", link: "/opcodes/OP_NOP7.md" },
        { text: "<code>183 | OP_NOP8</code>", link: "/opcodes/OP_NOP8.md" },
        { text: "<code>184 | OP_NOP9</code>", link: "/opcodes/OP_NOP9.md" },
        { text: "<code>185 | OP_NOP10</code>", link: "/opcodes/OP_NOP10.md" },
        { text: "<code>186 | 🚧 186 OP_CHECKSIGADD</code>", link: "/opcodes/WIP.md" },
        { text: "<code>187 | OP_RETURN_187</code>", link: "/opcodes/OP_RETURN_187.md" },
        { text: "<code>188 | OP_RETURN_188</code>", link: "/opcodes/OP_RETURN_188.md" },
        { text: "<code>189 | OP_RETURN_189</code>", link: "/opcodes/OP_RETURN_189.md" },
        { text: "<code>190 | OP_RETURN_190</code>", link: "/opcodes/OP_RETURN_190.md" },
        { text: "<code>191 | OP_RETURN_191</code>", link: "/opcodes/OP_RETURN_191.md" },
        { text: "<code>192 | OP_RETURN_192</code>", link: "/opcodes/OP_RETURN_192.md" },
        { text: "<code>193 | OP_RETURN_193</code>", link: "/opcodes/OP_RETURN_193.md" },
        { text: "<code>194 | OP_RETURN_194</code>", link: "/opcodes/OP_RETURN_194.md" },
        { text: "<code>195 | OP_RETURN_195</code>", link: "/opcodes/OP_RETURN_195.md" },
        { text: "<code>196 | OP_RETURN_196</code>", link: "/opcodes/OP_RETURN_196.md" },
        { text: "<code>197 | OP_RETURN_197</code>", link: "/opcodes/OP_RETURN_197.md" },
        { text: "<code>198 | OP_RETURN_198</code>", link: "/opcodes/OP_RETURN_198.md" },
        { text: "<code>199 | OP_RETURN_199</code>", link: "/opcodes/OP_RETURN_199.md" },
        { text: "<code>200 | OP_RETURN_200</code>", link: "/opcodes/OP_RETURN_200.md" },
        { text: "<code>201 | OP_RETURN_201</code>", link: "/opcodes/OP_RETURN_201.md" },
        { text: "<code>202 | OP_RETURN_202</code>", link: "/opcodes/OP_RETURN_202.md" },
        { text: "<code>203 | OP_RETURN_203</code>", link: "/opcodes/OP_RETURN_203.md" },
        { text: "<code>204 | OP_RETURN_204</code>", link: "/opcodes/OP_RETURN_204.md" },
        { text: "<code>205 | OP_RETURN_205</code>", link: "/opcodes/OP_RETURN_205.md" },
        { text: "<code>206 | OP_RETURN_206</code>", link: "/opcodes/OP_RETURN_206.md" },
        { text: "<code>207 | OP_RETURN_207</code>", link: "/opcodes/OP_RETURN_207.md" },
        { text: "<code>208 | OP_RETURN_208</code>", link: "/opcodes/OP_RETURN_208.md" },
        { text: "<code>209 | OP_RETURN_209</code>", link: "/opcodes/OP_RETURN_209.md" },
        { text: "<code>210 | OP_RETURN_210</code>", link: "/opcodes/OP_RETURN_210.md" },
        { text: "<code>211 | OP_RETURN_211</code>", link: "/opcodes/OP_RETURN_211.md" },
        { text: "<code>212 | OP_RETURN_212</code>", link: "/opcodes/OP_RETURN_212.md" },
        { text: "<code>213 | OP_RETURN_213</code>", link: "/opcodes/OP_RETURN_213.md" },
        { text: "<code>214 | OP_RETURN_214</code>", link: "/opcodes/OP_RETURN_214.md" },
        { text: "<code>215 | OP_RETURN_215</code>", link: "/opcodes/OP_RETURN_215.md" },
        { text: "<code>216 | OP_RETURN_216</code>", link: "/opcodes/OP_RETURN_216.md" },
        { text: "<code>217 | OP_RETURN_217</code>", link: "/opcodes/OP_RETURN_217.md" },
        { text: "<code>218 | OP_RETURN_218</code>", link: "/opcodes/OP_RETURN_218.md" },
        { text: "<code>219 | OP_RETURN_219</code>", link: "/opcodes/OP_RETURN_219.md" },
        { text: "<code>220 | OP_RETURN_220</code>", link: "/opcodes/OP_RETURN_220.md" },
        { text: "<code>220 | OP_RETURN_221</code>", link: "/opcodes/OP_RETURN_221.md" },
        { text: "<code>220 | OP_RETURN_222</code>", link: "/opcodes/OP_RETURN_222.md" },
        { text: "<code>220 | OP_RETURN_223</code>", link: "/opcodes/OP_RETURN_223.md" },
        { text: "<code>220 | OP_RETURN_224</code>", link: "/opcodes/OP_RETURN_224.md" },
        { text: "<code>220 | OP_RETURN_225</code>", link: "/opcodes/OP_RETURN_225.md" },
        { text: "<code>220 | OP_RETURN_226</code>", link: "/opcodes/OP_RETURN_226.md" },
        { text: "<code>220 | OP_RETURN_227</code>", link: "/opcodes/OP_RETURN_227.md" },
        { text: "<code>220 | OP_RETURN_228</code>", link: "/opcodes/OP_RETURN_228.md" },
        { text: "<code>220 | OP_RETURN_229</code>", link: "/opcodes/OP_RETURN_229.md" },
        { text: "<code>230 | OP_RETURN_230</code>", link: "/opcodes/OP_RETURN_230.md" },
        { text: "<code>231 | OP_RETURN_231</code>", link: "/opcodes/OP_RETURN_231.md" },
        { text: "<code>232 | OP_RETURN_232</code>", link: "/opcodes/OP_RETURN_232.md" },
        { text: "<code>233 | OP_RETURN_233</code>", link: "/opcodes/OP_RETURN_233.md" },
        { text: "<code>234 | OP_RETURN_234</code>", link: "/opcodes/OP_RETURN_234.md" },
        { text: "<code>235 | OP_RETURN_235</code>", link: "/opcodes/OP_RETURN_235.md" },
        { text: "<code>236 | OP_RETURN_236</code>", link: "/opcodes/OP_RETURN_236.md" },
        { text: "<code>237 | OP_RETURN_237</code>", link: "/opcodes/OP_RETURN_237.md" },
        { text: "<code>238 | OP_RETURN_238</code>", link: "/opcodes/OP_RETURN_238.md" },
        { text: "<code>239 | OP_RETURN_239</code>", link: "/opcodes/OP_RETURN_239.md" },
        { text: "<code>240 | OP_RETURN_240</code>", link: "/opcodes/OP_RETURN_240.md" },
        { text: "<code>241 | OP_RETURN_241</code>", link: "/opcodes/OP_RETURN_241.md" },
        { text: "<code>242 | OP_RETURN_242</code>", link: "/opcodes/OP_RETURN_242.md" },
        { text: "<code>243 | OP_RETURN_243</code>", link: "/opcodes/OP_RETURN_243.md" },
        { text: "<code>244 | OP_RETURN_244</code>", link: "/opcodes/OP_RETURN_244.md" },
        { text: "<code>245 | OP_RETURN_245</code>", link: "/opcodes/OP_RETURN_245.md" },
        { text: "<code>246 | OP_RETURN_246</code>", link: "/opcodes/OP_RETURN_246.md" },
        { text: "<code>247 | OP_RETURN_247</code>", link: "/opcodes/OP_RETURN_247.md" },
        { text: "<code>248 | OP_RETURN_248</code>", link: "/opcodes/OP_RETURN_248.md" },
        { text: "<code>249 | OP_RETURN_249</code>", link: "/opcodes/OP_RETURN_249.md" },
        { text: "<code>250 | OP_RETURN_250</code>", link: "/opcodes/OP_RETURN_250.md" },
        { text: "<code>251 | OP_RETURN_251</code>", link: "/opcodes/OP_RETURN_251.md" },
        { text: "<code>252 | OP_RETURN_252</code>", link: "/opcodes/OP_RETURN_252.md" },
        { text: "<code>253 | OP_RETURN_253</code>", link: "/opcodes/OP_RETURN_253.md" },
        { text: "<code>254 | OP_RETURN_254</code>", link: "/opcodes/OP_RETURN_254.md" },
        { text: "<code>255 | 🚧 OP_INVALIDOPCODE</code>", link: "/opcodes/WIP.md" },
      ],
      
      "/script/": [
        { text: "Script Basics", link: "/script/script_basics.md"},
        { text: "Script Success and Failure", link: "/script/script.md" },
        { text: "ASM Representation", link: "/script/asm.md" },
        { text: "Push Operators", link: "/script/push.md" },
        { text: "Numbers in Script", link: "/script/numbers.md" },
      ]
    },
    
    socialLinks: [
      { icon: "github", link: "https://github.com/thunderbiscuit/opcode-explained" }
    ]
  }
};
