import { defineConfig } from "vitepress"

export default defineConfig({
  title: "Opcode Explained",
  description: "Documenting bitcoin opcodes",
  themeConfig: {
    nav: [
      { text: "Opcodes", link: "/opcodes/", activeMatch: "/opcodes/" },
      { text: "Extras", link: "/overview/script-success.md", activeMatch: "/overview" }
    ],

    sidebar: {
      "/opcodes/": [
        { text: "<code>[ 0 ]</code>&nbsp;&nbsp; OP_0", link: "/opcodes/OP_0.md" },
        { text: "<code>[ 1 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_1", link: "/opcodes/OP_PUSHBYTES_1.md" },
        { text: "<code>[ 2 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_2", link: "/opcodes/OP_PUSHBYTES_2.md" },
        { text: "<code>[ 3 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_3", link: "/opcodes/OP_PUSHBYTES_3.md" },
        { text: "<code>[ 4 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_4", link: "/opcodes/OP_PUSHBYTES_4.md" },
        { text: "<code>[ 5 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_5", link: "/opcodes/OP_PUSHBYTES_5.md" },
        { text: "<code>[ 6 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_6", link: "/opcodes/OP_PUSHBYTES_6.md" },
        { text: "<code>[ 7 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_7", link: "/opcodes/OP_PUSHBYTES_7.md" },
        { text: "<code>[ 8 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_8", link: "/opcodes/OP_PUSHBYTES_8.md" },
        { text: "<code>[ 9 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_9", link: "/opcodes/OP_PUSHBYTES_9.md" },
        { text: "<code>[ 10 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_10", link: "/opcodes/OP_PUSHBYTES_10.md" },
        { text: "<code>[ 11 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_11", link: "/opcodes/OP_PUSHBYTES_11.md" },
        { text: "<code>[ 12 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_12", link: "/opcodes/OP_PUSHBYTES_12.md" },
        { text: "<code>[ 13 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_13", link: "/opcodes/OP_PUSHBYTES_13.md" },
        { text: "<code>[ 14 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_14", link: "/opcodes/OP_PUSHBYTES_14.md" },
        { text: "<code>[ 15 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_15", link: "/opcodes/OP_PUSHBYTES_15.md" },
        { text: "<code>[ 16 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_16", link: "/opcodes/OP_PUSHBYTES_16.md" },
        { text: "<code>[ 17 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_17", link: "/opcodes/OP_PUSHBYTES_17.md" },
        { text: "<code>[ 18 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_18", link: "/opcodes/OP_PUSHBYTES_18.md" },
        { text: "<code>[ 19 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_19", link: "/opcodes/OP_PUSHBYTES_19.md" },
        { text: "<code>[ 20 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_20", link: "/opcodes/OP_PUSHBYTES_20.md" },
        { text: "<code>[ 21 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_21", link: "/opcodes/OP_PUSHBYTES_21.md" },
        { text: "<code>[ 22 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_22", link: "/opcodes/OP_PUSHBYTES_22.md" },
        { text: "<code>[ 23 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_23", link: "/opcodes/OP_PUSHBYTES_23.md" },
        { text: "<code>[ 24 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_24", link: "/opcodes/OP_PUSHBYTES_24.md" },
        { text: "<code>[ 25 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_25", link: "/opcodes/OP_PUSHBYTES_25.md" },
        { text: "<code>[ 26 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_26", link: "/opcodes/OP_PUSHBYTES_26.md" },
        { text: "<code>[ 27 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_27", link: "/opcodes/OP_PUSHBYTES_27.md" },
        { text: "<code>[ 28 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_28", link: "/opcodes/OP_PUSHBYTES_28.md" },
        { text: "<code>[ 29 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_29", link: "/opcodes/OP_PUSHBYTES_29.md" },
        { text: "<code>[ 30 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_30", link: "/opcodes/OP_PUSHBYTES_30.md" },
        { text: "<code>[ 31 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_31", link: "/opcodes/OP_PUSHBYTES_31.md" },
        { text: "<code>[ 32 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_32", link: "/opcodes/OP_PUSHBYTES_32.md" },
        { text: "<code>[ 33 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_33", link: "/opcodes/OP_PUSHBYTES_33.md" },
        { text: "<code>[ 34 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_34", link: "/opcodes/OP_PUSHBYTES_34.md" },
        { text: "<code>[ 35 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_35", link: "/opcodes/OP_PUSHBYTES_35.md" },
        { text: "<code>[ 36 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_36", link: "/opcodes/OP_PUSHBYTES_36.md" },
        { text: "<code>[ 37 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_37", link: "/opcodes/OP_PUSHBYTES_37.md" },
        { text: "<code>[ 38 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_38", link: "/opcodes/OP_PUSHBYTES_38.md" },
        { text: "<code>[ 39 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_39", link: "/opcodes/OP_PUSHBYTES_39.md" },
        { text: "<code>[ 40 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_40", link: "/opcodes/OP_PUSHBYTES_40.md" },
        { text: "<code>[ 41 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_41", link: "/opcodes/OP_PUSHBYTES_41.md" },
        { text: "<code>[ 42 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_42", link: "/opcodes/OP_PUSHBYTES_42.md" },
        { text: "<code>[ 43 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_43", link: "/opcodes/OP_PUSHBYTES_43.md" },
        { text: "<code>[ 44 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_44", link: "/opcodes/OP_PUSHBYTES_44.md" },
        { text: "<code>[ 45 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_45", link: "/opcodes/OP_PUSHBYTES_45.md" },
        { text: "<code>[ 46 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_46", link: "/opcodes/OP_PUSHBYTES_46.md" },
        { text: "<code>[ 47 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_47", link: "/opcodes/OP_PUSHBYTES_47.md" },
        { text: "<code>[ 48 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_48", link: "/opcodes/OP_PUSHBYTES_48.md" },
        { text: "<code>[ 49 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_49", link: "/opcodes/OP_PUSHBYTES_49.md" },
        { text: "<code>[ 50 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_50", link: "/opcodes/OP_PUSHBYTES_50.md" },
        { text: "<code>[ 51 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_51", link: "/opcodes/OP_PUSHBYTES_51.md" },
        { text: "<code>[ 52 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_52", link: "/opcodes/OP_PUSHBYTES_52.md" },
        { text: "<code>[ 53 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_53", link: "/opcodes/OP_PUSHBYTES_53.md" },
        { text: "<code>[ 54 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_54", link: "/opcodes/OP_PUSHBYTES_54.md" },
        { text: "<code>[ 55 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_55", link: "/opcodes/OP_PUSHBYTES_55.md" },
        { text: "<code>[ 56 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_56", link: "/opcodes/OP_PUSHBYTES_56.md" },
        { text: "<code>[ 57 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_57", link: "/opcodes/OP_PUSHBYTES_57.md" },
        { text: "<code>[ 58 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_58", link: "/opcodes/OP_PUSHBYTES_58.md" },
        { text: "<code>[ 59 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_59", link: "/opcodes/OP_PUSHBYTES_59.md" },
        { text: "<code>[ 60 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_60", link: "/opcodes/OP_PUSHBYTES_60.md" },
        { text: "<code>[ 61 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_61", link: "/opcodes/OP_PUSHBYTES_61.md" },
        { text: "<code>[ 62 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_62", link: "/opcodes/OP_PUSHBYTES_62.md" },
        { text: "<code>[ 63 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_63", link: "/opcodes/OP_PUSHBYTES_63.md" },
        { text: "<code>[ 64 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_64", link: "/opcodes/OP_PUSHBYTES_64.md" },
        { text: "<code>[ 65 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_65", link: "/opcodes/OP_PUSHBYTES_65.md" },
        { text: "<code>[ 66 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_66", link: "/opcodes/OP_PUSHBYTES_66.md" },
        { text: "<code>[ 67 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_67", link: "/opcodes/OP_PUSHBYTES_67.md" },
        { text: "<code>[ 68 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_68", link: "/opcodes/OP_PUSHBYTES_68.md" },
        { text: "<code>[ 69 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_69", link: "/opcodes/OP_PUSHBYTES_69.md" },
        { text: "<code>[ 70 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_70", link: "/opcodes/OP_PUSHBYTES_70.md" },
        { text: "<code>[ 71 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_71", link: "/opcodes/OP_PUSHBYTES_71.md" },
        { text: "<code>[ 72 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_72", link: "/opcodes/OP_PUSHBYTES_72.md" },
        { text: "<code>[ 73 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_73", link: "/opcodes/OP_PUSHBYTES_73.md" },
        { text: "<code>[ 74 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_74", link: "/opcodes/OP_PUSHBYTES_74.md" },
        { text: "<code>[ 75 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_75", link: "/opcodes/OP_PUSHBYTES_75.md" },
        { text: "<code>[ 76 ]</code>&nbsp;&nbsp; OP_PUSHDATA1", link: "/opcodes/OP_PUSHDATA1.md" },
        { text: "<code>[ 77 ]</code>&nbsp;&nbsp; OP_PUSHDATA2", link: "/opcodes/OP_PUSHDATA2.md" },
        { text: "<code>[ 78 ]</code>&nbsp;&nbsp; OP_PUSHDATA4", link: "/opcodes/OP_PUSHDATA4.md" },
        { text: "<code>[ 79 ]</code>&nbsp;&nbsp; OP_1NEGATE", link: "/opcodes/OP_1NEGATE.md" },
        { text: "<code>[ 80 ]</code>&nbsp;&nbsp; OP_RESERVED", link: "/opcodes/OP_RESERVED.md" },
        { text: "<code>[ 81 ]</code>&nbsp;&nbsp; OP_1", link: "/opcodes/OP_1.md" },
        { text: "<code>[ 82 ]</code>&nbsp;&nbsp; OP_2", link: "/opcodes/OP_2.md" },
        { text: "<code>[ 83 ]</code>&nbsp;&nbsp; OP_3", link: "/opcodes/OP_3.md" },
        { text: "<code>[ 84 ]</code>&nbsp;&nbsp; OP_4", link: "/opcodes/OP_4.md" },
        { text: "<code>[ 85 ]</code>&nbsp;&nbsp; OP_5", link: "/opcodes/OP_5.md" },
        { text: "<code>[ 86 ]</code>&nbsp;&nbsp; OP_6", link: "/opcodes/OP_6.md" },
        { text: "<code>[ 87 ]</code>&nbsp;&nbsp; OP_7", link: "/opcodes/OP_7.md" },
        { text: "<code>[ 88 ]</code>&nbsp;&nbsp; OP_8", link: "/opcodes/OP_8.md" },
        { text: "<code>[ 89 ]</code>&nbsp;&nbsp; OP_9", link: "/opcodes/OP_9.md" },
        { text: "<code>[ 90 ]</code>&nbsp;&nbsp; OP_10", link: "/opcodes/OP_10.md" },
        { text: "<code>[ 91 ]</code>&nbsp;&nbsp; OP_11", link: "/opcodes/OP_11.md" },
        { text: "<code>[ 92 ]</code>&nbsp;&nbsp; OP_12", link: "/opcodes/OP_12.md" },
        { text: "<code>[ 93 ]</code>&nbsp;&nbsp; OP_13", link: "/opcodes/OP_13.md" },
        { text: "<code>[ 94 ]</code>&nbsp;&nbsp; OP_14", link: "/opcodes/OP_14.md" },
        { text: "<code>[ 95 ]</code>&nbsp;&nbsp; OP_15", link: "/opcodes/OP_15.md" },
        { text: "<code>[ 96 ]</code>&nbsp;&nbsp; OP_16", link: "/opcodes/OP_16.md" },
        { text: "<code>[ 97 ]</code>&nbsp;&nbsp; OP_NOP", link: "/opcodes/OP_NOP.md" },
        { text: "<code>[ 98 ]</code>&nbsp;&nbsp; OP_VER", link: "/opcodes/OP_VER.md" },
        
        { text: "<code>[ 147 ]</code>&nbsp;&nbsp; OP_ADD", link: "/opcodes/OP_ADD.md" },
        { text: "<code>[ 176 ]</code>&nbsp;&nbsp; OP_NOP1", link: "/opcodes/OP_NOP1.md" },
        { text: "<code>[ 179 ]</code>&nbsp;&nbsp; OP_NOP4", link: "/opcodes/OP_NOP4.md" },
        { text: "<code>[ 180 ]</code>&nbsp;&nbsp; OP_NOP5", link: "/opcodes/OP_NOP5.md" },
        { text: "<code>[ 181 ]</code>&nbsp;&nbsp; OP_NOP6", link: "/opcodes/OP_NOP6.md" },
        { text: "<code>[ 182 ]</code>&nbsp;&nbsp; OP_NOP7", link: "/opcodes/OP_NOP7.md" },
      ],
      
      "/overview/": [
        { text: "Bitcoin Script Success/Failure", link: "/overview/script-success.md" },
        { text: "ASM Representation", link: "/overview/asm.md" },
        { text: "Numbers in Script", link: "/overview/numbers.md" },
      ]
    },
    
    socialLinks: [
      { icon: "github", link: "https://github.com/thunderbiscuit/opcode-explained" }
    ]
  }
})
