import { defineConfig } from "vitepress"

export default defineConfig({
  title: "Opcode Explained",
  description: "Documenting bitcoin opcodes",
  themeConfig: {
    search: {
      provider: "local"
    },

    nav: [
      { text: "Opcodes", link: "/opcodes/", activeMatch: "/opcodes/" },
      { text: "Script", link: "/script/", activeMatch: "/script/" }
    ],

    sidebar: {
      "/opcodes/": [
        { text: "<code>[ 0 ]</code>&nbsp;&nbsp; OP_0", link: "/opcodes/OP_0.md" },
        { text: "<code>[ 1 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_1", link: "/opcodes/OP_PUSHBYTES_1.md" },
        { text: "<code>[ 2 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_2", link: "/opcodes/OP_PUSHBYTES_2.md" },
        { text: "<code>[ 3 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_3", link: "/opcodes/OP_PUSHBYTES_3.md" },
        { text: "<code>[ 4 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_4", link: "/opcodes/OP_PUSHBYTES_4.md" },
        { text: "<code>[ 5 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_5", link: "/opcodes/OP_PUSHBYTES_5.md" },
        { text: "<code>[ 6 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_6", link: "/opcodes/OP_PUSHBYTES_6.md" },
        { text: "<code>[ 7 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_7", link: "/opcodes/OP_PUSHBYTES_7.md" },
        { text: "<code>[ 8 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_8", link: "/opcodes/OP_PUSHBYTES_8.md" },
        { text: "<code>[ 9 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_9", link: "/opcodes/OP_PUSHBYTES_9.md" },
        { text: "<code>[ 10 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_10", link: "/opcodes/OP_PUSHBYTES_10.md" },
        { text: "<code>[ 11 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_11", link: "/opcodes/OP_PUSHBYTES_11.md" },
        { text: "<code>[ 12 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_12", link: "/opcodes/OP_PUSHBYTES_12.md" },
        { text: "<code>[ 13 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_13", link: "/opcodes/OP_PUSHBYTES_13.md" },
        { text: "<code>[ 14 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_14", link: "/opcodes/OP_PUSHBYTES_14.md" },
        { text: "<code>[ 15 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_15", link: "/opcodes/OP_PUSHBYTES_15.md" },
        { text: "<code>[ 16 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_16", link: "/opcodes/OP_PUSHBYTES_16.md" },
        { text: "<code>[ 17 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_17", link: "/opcodes/OP_PUSHBYTES_17.md" },
        { text: "<code>[ 18 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_18", link: "/opcodes/OP_PUSHBYTES_18.md" },
        { text: "<code>[ 19 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_19", link: "/opcodes/OP_PUSHBYTES_19.md" },
        { text: "<code>[ 20 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_20", link: "/opcodes/OP_PUSHBYTES_20.md" },
        { text: "<code>[ 21 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_21", link: "/opcodes/OP_PUSHBYTES_21.md" },
        { text: "<code>[ 22 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_22", link: "/opcodes/OP_PUSHBYTES_22.md" },
        { text: "<code>[ 23 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_23", link: "/opcodes/OP_PUSHBYTES_23.md" },
        { text: "<code>[ 24 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_24", link: "/opcodes/OP_PUSHBYTES_24.md" },
        { text: "<code>[ 25 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_25", link: "/opcodes/OP_PUSHBYTES_25.md" },
        { text: "<code>[ 26 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_26", link: "/opcodes/OP_PUSHBYTES_26.md" },
        { text: "<code>[ 27 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_27", link: "/opcodes/OP_PUSHBYTES_27.md" },
        { text: "<code>[ 28 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_28", link: "/opcodes/OP_PUSHBYTES_28.md" },
        { text: "<code>[ 29 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_29", link: "/opcodes/OP_PUSHBYTES_29.md" },
        { text: "<code>[ 30 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_30", link: "/opcodes/OP_PUSHBYTES_30.md" },
        { text: "<code>[ 31 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_31", link: "/opcodes/OP_PUSHBYTES_31.md" },
        { text: "<code>[ 32 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_32", link: "/opcodes/OP_PUSHBYTES_32.md" },
        { text: "<code>[ 33 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_33", link: "/opcodes/OP_PUSHBYTES_33.md" },
        { text: "<code>[ 34 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_34", link: "/opcodes/OP_PUSHBYTES_34.md" },
        { text: "<code>[ 35 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_35", link: "/opcodes/OP_PUSHBYTES_35.md" },
        { text: "<code>[ 36 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_36", link: "/opcodes/OP_PUSHBYTES_36.md" },
        { text: "<code>[ 37 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_37", link: "/opcodes/OP_PUSHBYTES_37.md" },
        { text: "<code>[ 38 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_38", link: "/opcodes/OP_PUSHBYTES_38.md" },
        { text: "<code>[ 39 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_39", link: "/opcodes/OP_PUSHBYTES_39.md" },
        { text: "<code>[ 40 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_40", link: "/opcodes/OP_PUSHBYTES_40.md" },
        { text: "<code>[ 41 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_41", link: "/opcodes/OP_PUSHBYTES_41.md" },
        { text: "<code>[ 42 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_42", link: "/opcodes/OP_PUSHBYTES_42.md" },
        { text: "<code>[ 43 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_43", link: "/opcodes/OP_PUSHBYTES_43.md" },
        { text: "<code>[ 44 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_44", link: "/opcodes/OP_PUSHBYTES_44.md" },
        { text: "<code>[ 45 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_45", link: "/opcodes/OP_PUSHBYTES_45.md" },
        { text: "<code>[ 46 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_46", link: "/opcodes/OP_PUSHBYTES_46.md" },
        { text: "<code>[ 47 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_47", link: "/opcodes/OP_PUSHBYTES_47.md" },
        { text: "<code>[ 48 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_48", link: "/opcodes/OP_PUSHBYTES_48.md" },
        { text: "<code>[ 49 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_49", link: "/opcodes/OP_PUSHBYTES_49.md" },
        { text: "<code>[ 50 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_50", link: "/opcodes/OP_PUSHBYTES_50.md" },
        { text: "<code>[ 51 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_51", link: "/opcodes/OP_PUSHBYTES_51.md" },
        { text: "<code>[ 52 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_52", link: "/opcodes/OP_PUSHBYTES_52.md" },
        { text: "<code>[ 53 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_53", link: "/opcodes/OP_PUSHBYTES_53.md" },
        { text: "<code>[ 54 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_54", link: "/opcodes/OP_PUSHBYTES_54.md" },
        { text: "<code>[ 55 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_55", link: "/opcodes/OP_PUSHBYTES_55.md" },
        { text: "<code>[ 56 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_56", link: "/opcodes/OP_PUSHBYTES_56.md" },
        { text: "<code>[ 57 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_57", link: "/opcodes/OP_PUSHBYTES_57.md" },
        { text: "<code>[ 58 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_58", link: "/opcodes/OP_PUSHBYTES_58.md" },
        { text: "<code>[ 59 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_59", link: "/opcodes/OP_PUSHBYTES_59.md" },
        { text: "<code>[ 60 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_60", link: "/opcodes/OP_PUSHBYTES_60.md" },
        { text: "<code>[ 61 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_61", link: "/opcodes/OP_PUSHBYTES_61.md" },
        { text: "<code>[ 62 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_62", link: "/opcodes/OP_PUSHBYTES_62.md" },
        { text: "<code>[ 63 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_63", link: "/opcodes/OP_PUSHBYTES_63.md" },
        { text: "<code>[ 64 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_64", link: "/opcodes/OP_PUSHBYTES_64.md" },
        { text: "<code>[ 65 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_65", link: "/opcodes/OP_PUSHBYTES_65.md" },
        { text: "<code>[ 66 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_66", link: "/opcodes/OP_PUSHBYTES_66.md" },
        { text: "<code>[ 67 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_67", link: "/opcodes/OP_PUSHBYTES_67.md" },
        { text: "<code>[ 68 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_68", link: "/opcodes/OP_PUSHBYTES_68.md" },
        { text: "<code>[ 69 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_69", link: "/opcodes/OP_PUSHBYTES_69.md" },
        { text: "<code>[ 70 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_70", link: "/opcodes/OP_PUSHBYTES_70.md" },
        { text: "<code>[ 71 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_71", link: "/opcodes/OP_PUSHBYTES_71.md" },
        { text: "<code>[ 72 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_72", link: "/opcodes/OP_PUSHBYTES_72.md" },
        { text: "<code>[ 73 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_73", link: "/opcodes/OP_PUSHBYTES_73.md" },
        { text: "<code>[ 74 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_74", link: "/opcodes/OP_PUSHBYTES_74.md" },
        { text: "<code>[ 75 ]</code>&nbsp;&nbsp; OP_PUSHBYTES_75", link: "/opcodes/OP_PUSHBYTES_75.md" },
        { text: "<code>[ 76 ]</code>&nbsp;&nbsp; OP_PUSHDATA1", link: "/opcodes/OP_PUSHDATA1.md" },
        { text: "<code>[ 77 ]</code>&nbsp;&nbsp; OP_PUSHDATA2", link: "/opcodes/OP_PUSHDATA2.md" },
        { text: "<code>[ 78 ]</code>&nbsp;&nbsp; OP_PUSHDATA4", link: "/opcodes/OP_PUSHDATA4.md" },
        { text: "<code>[ 79 ]</code>&nbsp;&nbsp; OP_1NEGATE", link: "/opcodes/OP_1NEGATE.md" },
        { text: "<code>[ 80 ]</code>&nbsp;&nbsp; OP_RESERVED", link: "/opcodes/OP_RESERVED.md" },
        { text: "<code>[ 81 ]</code>&nbsp;&nbsp; OP_1", link: "/opcodes/OP_1.md" },
        { text: "<code>[ 82 ]</code>&nbsp;&nbsp; OP_2", link: "/opcodes/OP_2.md" },
        { text: "<code>[ 83 ]</code>&nbsp;&nbsp; OP_3", link: "/opcodes/OP_3.md" },
        { text: "<code>[ 84 ]</code>&nbsp;&nbsp; OP_4", link: "/opcodes/OP_4.md" },
        { text: "<code>[ 85 ]</code>&nbsp;&nbsp; OP_5", link: "/opcodes/OP_5.md" },
        { text: "<code>[ 86 ]</code>&nbsp;&nbsp; OP_6", link: "/opcodes/OP_6.md" },
        { text: "<code>[ 87 ]</code>&nbsp;&nbsp; OP_7", link: "/opcodes/OP_7.md" },
        { text: "<code>[ 88 ]</code>&nbsp;&nbsp; OP_8", link: "/opcodes/OP_8.md" },
        { text: "<code>[ 89 ]</code>&nbsp;&nbsp; OP_9", link: "/opcodes/OP_9.md" },
        { text: "<code>[ 90 ]</code>&nbsp;&nbsp; OP_10", link: "/opcodes/OP_10.md" },
        { text: "<code>[ 91 ]</code>&nbsp;&nbsp; OP_11", link: "/opcodes/OP_11.md" },
        { text: "<code>[ 92 ]</code>&nbsp;&nbsp; OP_12", link: "/opcodes/OP_12.md" },
        { text: "<code>[ 93 ]</code>&nbsp;&nbsp; OP_13", link: "/opcodes/OP_13.md" },
        { text: "<code>[ 94 ]</code>&nbsp;&nbsp; OP_14", link: "/opcodes/OP_14.md" },
        { text: "<code>[ 95 ]</code>&nbsp;&nbsp; OP_15", link: "/opcodes/OP_15.md" },
        { text: "<code>[ 96 ]</code>&nbsp;&nbsp; OP_16", link: "/opcodes/OP_16.md" },
        { text: "<code>[ 97 ]</code>&nbsp;&nbsp; OP_NOP", link: "/opcodes/OP_NOP.md" },
        { text: "<code>[ 98 ]</code>&nbsp;&nbsp; OP_VER", link: "/opcodes/OP_VER.md" },
        { text: "<code>[ 99 ]</code>&nbsp;&nbsp; OP_IF", link: "/opcodes/OP_IF.md" },
        { text: "<code>[ 100 ]</code>&nbsp;&nbsp; OP_NOTIF", link: "/opcodes/OP_NOTIF.md" },
        { text: "<code>[ 101 ]</code>&nbsp;&nbsp; OP_VERIF", link: "/opcodes/OP_VERIF.md" },
        { text: "<code>[ 102 ]</code>&nbsp;&nbsp; OP_VERNOTIF", link: "/opcodes/OP_VERNOTIF.md" },
        { text: "<code>[ 103 ]</code>&nbsp;&nbsp; OP_ELSE", link: "/opcodes/OP_ELSE.md" },
        { text: "<code>[ 104 ]</code>&nbsp;&nbsp; OP_ENDIF", link: "/opcodes/OP_ENDIF.md" },
        { text: "<code>[ 105 ]</code>&nbsp;&nbsp; OP_VERIFY", link: "/opcodes/OP_VERIFY.md" },
        { text: "<code>[ 106 ]</code>&nbsp;&nbsp; OP_RETURN", link: "/opcodes/OP_RETURN.md" },
        { text: "<code>[ 107 ]</code>&nbsp;&nbsp; OP_TOALTSTACK", link: "/opcodes/OP_TOALTSTACK.md" },
        { text: "<code>[ 108 ]</code>&nbsp;&nbsp; OP_FROMALTSTACK", link: "/opcodes/OP_FROMALTSTACK.md" },        
        { text: "<code>[ 109 ]</code>&nbsp;&nbsp; OP_2DROP", link: "/opcodes/OP_2DROP.md" },

        { text: "🚧 110 OP_2DUP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 111 OP_3DUP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 112 OP_2OVER 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 113 OP_2ROT 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 114 OP_2SWAP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 115 OP_IFDUP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 116 OP_DEPTH 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 117 OP_DROP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 118 OP_DUP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 119 OP_NIP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 120 OP_OVER 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 121 OP_PICK 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 122 OP_ROLL 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 123 OP_ROT 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 124 OP_SWAP 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 125 OP_TUCK 🚧", link: "/opcodes/WIP.md" },
        
        { text: "<code>[ 126 ]</code>&nbsp;&nbsp; OP_CAT", link: "/opcodes/OP_CAT.md" },
        { text: "<code>[ 127 ]</code>&nbsp;&nbsp; OP_SUBSTR", link: "/opcodes/OP_SUBSTR.md" },
        { text: "<code>[ 128 ]</code>&nbsp;&nbsp; OP_LEFT", link: "/opcodes/OP_LEFT.md" },
        { text: "<code>[ 129 ]</code>&nbsp;&nbsp; OP_RIGHT", link: "/opcodes/OP_RIGHT.md" },
        
        { text: "🚧 130 OP_SIZE 🚧", link: "/opcodes/WIP.md" },
        
        { text: "<code>[ 131 ]</code>&nbsp;&nbsp; OP_INVERT", link: "/opcodes/OP_INVERT.md" },
        { text: "<code>[ 132 ]</code>&nbsp;&nbsp; OP_AND", link: "/opcodes/OP_AND.md" },
        { text: "<code>[ 133 ]</code>&nbsp;&nbsp; OP_OR", link: "/opcodes/OP_OR.md" },
        { text: "<code>[ 134 ]</code>&nbsp;&nbsp; OP_XOR", link: "/opcodes/OP_XOR.md" },
        
        { text: "🚧 135 OP_EQUAL 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 136 OP_EQUALVERIFY 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 137 OP_RESERVED1 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 138 OP_RESERVED2 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 139 OP_1ADD 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 140 OP_1SUB 🚧", link: "/opcodes/WIP.md" },
        
        { text: "<code>[ 141 ]</code>&nbsp;&nbsp; OP_2MUL", link: "/opcodes/OP_2MUL.md" },
        { text: "<code>[ 142 ]</code>&nbsp;&nbsp; OP_2DIV", link: "/opcodes/OP_2DIV.md" },
        
        { text: "🚧 143 OP_NEGATE 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 144 OP_ABS 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 145 OP_NOT 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 146 OP_0NOTEQUAL 🚧", link: "/opcodes/WIP.md" },

        { text: "<code>[ 147 ]</code>&nbsp;&nbsp; OP_ADD", link: "/opcodes/OP_ADD.md" },

        { text: "🚧 148 OP_SUB 🚧", link: "/opcodes/WIP.md" },
        
        { text: "<code>[ 149 ]</code>&nbsp;&nbsp; OP_MUL", link: "/opcodes/OP_MUL.md" },
        { text: "<code>[ 150 ]</code>&nbsp;&nbsp; OP_DIV", link: "/opcodes/OP_DIV.md" },
        { text: "<code>[ 151 ]</code>&nbsp;&nbsp; OP_MOD", link: "/opcodes/OP_MOD.md" },
        { text: "<code>[ 152 ]</code>&nbsp;&nbsp; OP_LSHIFT", link: "/opcodes/OP_LSHIFT.md" },
        { text: "<code>[ 153 ]</code>&nbsp;&nbsp; OP_RSHIFT", link: "/opcodes/OP_RSHIFT.md" },
        
        { text: "🚧 154 OP_BOOLAND 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 155 OP_BOOLOR 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 156 OP_NUMEQUAL 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 157 OP_NUMEQUALVERIFY 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 158 OP_NUMNOTEQUAL 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 159 OP_LESSTHAN 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 160 OP_GREATERTHAN 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 161 OP_LESSTHANOREQUAL 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 162 OP_GREATERTHANOREQUAL 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 163 OP_MIN 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 164 OP_MAX 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 165 OP_WITHIN 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 166 OP_RIPEMD160 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 167 OP_SHA1 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 168 OP_SHA256 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 169 OP_HASH160 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 170 OP_HASH256 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 171 OP_CODESEPARATOR 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 172 OP_CHECKSIG 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 173 OP_CHECKSIGVERIFY 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 174 OP_CHECKMULTISIG 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 175 OP_CHECKMULTISIGVERIFY 🚧", link: "/opcodes/WIP.md" },

        { text: "<code>[ 176 ]</code>&nbsp;&nbsp; OP_NOP1", link: "/opcodes/OP_NOP1.md" },

        { text: "🚧 177 OP_CLTV 🚧", link: "/opcodes/WIP.md" },
        { text: "🚧 178 OP_CSV 🚧", link: "/opcodes/WIP.md" },

        { text: "<code>[ 179 ]</code>&nbsp;&nbsp; OP_NOP4", link: "/opcodes/OP_NOP4.md" },
        { text: "<code>[ 180 ]</code>&nbsp;&nbsp; OP_NOP5", link: "/opcodes/OP_NOP5.md" },
        { text: "<code>[ 181 ]</code>&nbsp;&nbsp; OP_NOP6", link: "/opcodes/OP_NOP6.md" },
        { text: "<code>[ 182 ]</code>&nbsp;&nbsp; OP_NOP7", link: "/opcodes/OP_NOP7.md" },
        { text: "<code>[ 183 ]</code>&nbsp;&nbsp; OP_NOP8", link: "/opcodes/OP_NOP8.md" },
        { text: "<code>[ 184 ]</code>&nbsp;&nbsp; OP_NOP9", link: "/opcodes/OP_NOP9.md" },
        { text: "<code>[ 185 ]</code>&nbsp;&nbsp; OP_NOP10", link: "/opcodes/OP_NOP10.md" },

        { text: "🚧 186 OP_CHECKSIGADD 🚧", link: "/opcodes/WIP.md" },

        { text: "<code>[ 187 ]</code>&nbsp;&nbsp; OP_RETURN_187", link: "/opcodes/OP_RETURN_187.md" },
        { text: "<code>[ 188 ]</code>&nbsp;&nbsp; OP_RETURN_188", link: "/opcodes/OP_RETURN_188.md" },
        { text: "<code>[ 189 ]</code>&nbsp;&nbsp; OP_RETURN_189", link: "/opcodes/OP_RETURN_189.md" },
        { text: "<code>[ 190 ]</code>&nbsp;&nbsp; OP_RETURN_190", link: "/opcodes/OP_RETURN_190.md" },
        { text: "<code>[ 191 ]</code>&nbsp;&nbsp; OP_RETURN_191", link: "/opcodes/OP_RETURN_191.md" },
        { text: "<code>[ 192 ]</code>&nbsp;&nbsp; OP_RETURN_192", link: "/opcodes/OP_RETURN_192.md" },
        { text: "<code>[ 193 ]</code>&nbsp;&nbsp; OP_RETURN_193", link: "/opcodes/OP_RETURN_193.md" },
        { text: "<code>[ 194 ]</code>&nbsp;&nbsp; OP_RETURN_194", link: "/opcodes/OP_RETURN_194.md" },
        { text: "<code>[ 195 ]</code>&nbsp;&nbsp; OP_RETURN_195", link: "/opcodes/OP_RETURN_195.md" },
        { text: "<code>[ 196 ]</code>&nbsp;&nbsp; OP_RETURN_196", link: "/opcodes/OP_RETURN_196.md" },
        { text: "<code>[ 197 ]</code>&nbsp;&nbsp; OP_RETURN_197", link: "/opcodes/OP_RETURN_197.md" },
        { text: "<code>[ 198 ]</code>&nbsp;&nbsp; OP_RETURN_198", link: "/opcodes/OP_RETURN_198.md" },
        { text: "<code>[ 199 ]</code>&nbsp;&nbsp; OP_RETURN_199", link: "/opcodes/OP_RETURN_199.md" },
        { text: "<code>[ 200 ]</code>&nbsp;&nbsp; OP_RETURN_200", link: "/opcodes/OP_RETURN_200.md" },
        { text: "<code>[ 201 ]</code>&nbsp;&nbsp; OP_RETURN_201", link: "/opcodes/OP_RETURN_201.md" },
        { text: "<code>[ 202 ]</code>&nbsp;&nbsp; OP_RETURN_202", link: "/opcodes/OP_RETURN_202.md" },
        { text: "<code>[ 203 ]</code>&nbsp;&nbsp; OP_RETURN_203", link: "/opcodes/OP_RETURN_203.md" },
        { text: "<code>[ 204 ]</code>&nbsp;&nbsp; OP_RETURN_204", link: "/opcodes/OP_RETURN_204.md" },
        { text: "<code>[ 205 ]</code>&nbsp;&nbsp; OP_RETURN_205", link: "/opcodes/OP_RETURN_205.md" },
        { text: "<code>[ 206 ]</code>&nbsp;&nbsp; OP_RETURN_206", link: "/opcodes/OP_RETURN_206.md" },
        { text: "<code>[ 207 ]</code>&nbsp;&nbsp; OP_RETURN_207", link: "/opcodes/OP_RETURN_207.md" },
        { text: "<code>[ 208 ]</code>&nbsp;&nbsp; OP_RETURN_208", link: "/opcodes/OP_RETURN_208.md" },
        { text: "<code>[ 209 ]</code>&nbsp;&nbsp; OP_RETURN_209", link: "/opcodes/OP_RETURN_209.md" },
        { text: "<code>[ 210 ]</code>&nbsp;&nbsp; OP_RETURN_210", link: "/opcodes/OP_RETURN_210.md" },
        { text: "<code>[ 211 ]</code>&nbsp;&nbsp; OP_RETURN_211", link: "/opcodes/OP_RETURN_211.md" },
        { text: "<code>[ 212 ]</code>&nbsp;&nbsp; OP_RETURN_212", link: "/opcodes/OP_RETURN_212.md" },
        { text: "<code>[ 213 ]</code>&nbsp;&nbsp; OP_RETURN_213", link: "/opcodes/OP_RETURN_213.md" },
        { text: "<code>[ 214 ]</code>&nbsp;&nbsp; OP_RETURN_214", link: "/opcodes/OP_RETURN_214.md" },
        { text: "<code>[ 215 ]</code>&nbsp;&nbsp; OP_RETURN_215", link: "/opcodes/OP_RETURN_215.md" },
        { text: "<code>[ 216 ]</code>&nbsp;&nbsp; OP_RETURN_216", link: "/opcodes/OP_RETURN_216.md" },
        { text: "<code>[ 217 ]</code>&nbsp;&nbsp; OP_RETURN_217", link: "/opcodes/OP_RETURN_217.md" },
        { text: "<code>[ 218 ]</code>&nbsp;&nbsp; OP_RETURN_218", link: "/opcodes/OP_RETURN_218.md" },
        { text: "<code>[ 219 ]</code>&nbsp;&nbsp; OP_RETURN_219", link: "/opcodes/OP_RETURN_219.md" },
        { text: "<code>[ 220 ]</code>&nbsp;&nbsp; OP_RETURN_220", link: "/opcodes/OP_RETURN_220.md" },
        { text: "<code>[ 221 ]</code>&nbsp;&nbsp; OP_RETURN_221", link: "/opcodes/OP_RETURN_221.md" },
        { text: "<code>[ 222 ]</code>&nbsp;&nbsp; OP_RETURN_222", link: "/opcodes/OP_RETURN_222.md" },
        { text: "<code>[ 223 ]</code>&nbsp;&nbsp; OP_RETURN_223", link: "/opcodes/OP_RETURN_223.md" },
        { text: "<code>[ 224 ]</code>&nbsp;&nbsp; OP_RETURN_224", link: "/opcodes/OP_RETURN_224.md" },
        { text: "<code>[ 225 ]</code>&nbsp;&nbsp; OP_RETURN_225", link: "/opcodes/OP_RETURN_225.md" },
        { text: "<code>[ 226 ]</code>&nbsp;&nbsp; OP_RETURN_226", link: "/opcodes/OP_RETURN_226.md" },
        { text: "<code>[ 227 ]</code>&nbsp;&nbsp; OP_RETURN_227", link: "/opcodes/OP_RETURN_227.md" },
        { text: "<code>[ 228 ]</code>&nbsp;&nbsp; OP_RETURN_228", link: "/opcodes/OP_RETURN_228.md" },
        { text: "<code>[ 229 ]</code>&nbsp;&nbsp; OP_RETURN_229", link: "/opcodes/OP_RETURN_229.md" },
        { text: "<code>[ 230 ]</code>&nbsp;&nbsp; OP_RETURN_230", link: "/opcodes/OP_RETURN_230.md" },
        { text: "<code>[ 231 ]</code>&nbsp;&nbsp; OP_RETURN_231", link: "/opcodes/OP_RETURN_231.md" },
        { text: "<code>[ 232 ]</code>&nbsp;&nbsp; OP_RETURN_232", link: "/opcodes/OP_RETURN_232.md" },
        { text: "<code>[ 233 ]</code>&nbsp;&nbsp; OP_RETURN_233", link: "/opcodes/OP_RETURN_233.md" },
        { text: "<code>[ 234 ]</code>&nbsp;&nbsp; OP_RETURN_234", link: "/opcodes/OP_RETURN_234.md" },
        { text: "<code>[ 235 ]</code>&nbsp;&nbsp; OP_RETURN_235", link: "/opcodes/OP_RETURN_235.md" },
        { text: "<code>[ 236 ]</code>&nbsp;&nbsp; OP_RETURN_236", link: "/opcodes/OP_RETURN_236.md" },
        { text: "<code>[ 237 ]</code>&nbsp;&nbsp; OP_RETURN_237", link: "/opcodes/OP_RETURN_237.md" },
        { text: "<code>[ 238 ]</code>&nbsp;&nbsp; OP_RETURN_238", link: "/opcodes/OP_RETURN_238.md" },
        { text: "<code>[ 239 ]</code>&nbsp;&nbsp; OP_RETURN_239", link: "/opcodes/OP_RETURN_239.md" },
        { text: "<code>[ 240 ]</code>&nbsp;&nbsp; OP_RETURN_240", link: "/opcodes/OP_RETURN_240.md" },
        { text: "<code>[ 241 ]</code>&nbsp;&nbsp; OP_RETURN_241", link: "/opcodes/OP_RETURN_241.md" },
        { text: "<code>[ 242 ]</code>&nbsp;&nbsp; OP_RETURN_242", link: "/opcodes/OP_RETURN_242.md" },
        { text: "<code>[ 243 ]</code>&nbsp;&nbsp; OP_RETURN_243", link: "/opcodes/OP_RETURN_243.md" },
        { text: "<code>[ 244 ]</code>&nbsp;&nbsp; OP_RETURN_244", link: "/opcodes/OP_RETURN_244.md" },
        { text: "<code>[ 245 ]</code>&nbsp;&nbsp; OP_RETURN_245", link: "/opcodes/OP_RETURN_245.md" },
        { text: "<code>[ 246 ]</code>&nbsp;&nbsp; OP_RETURN_246", link: "/opcodes/OP_RETURN_246.md" },
        { text: "<code>[ 247 ]</code>&nbsp;&nbsp; OP_RETURN_247", link: "/opcodes/OP_RETURN_247.md" },
        { text: "<code>[ 248 ]</code>&nbsp;&nbsp; OP_RETURN_248", link: "/opcodes/OP_RETURN_248.md" },
        { text: "<code>[ 249 ]</code>&nbsp;&nbsp; OP_RETURN_249", link: "/opcodes/OP_RETURN_249.md" },
        { text: "<code>[ 250 ]</code>&nbsp;&nbsp; OP_RETURN_250", link: "/opcodes/OP_RETURN_250.md" },
        { text: "<code>[ 251 ]</code>&nbsp;&nbsp; OP_RETURN_251", link: "/opcodes/OP_RETURN_251.md" },
        { text: "<code>[ 252 ]</code>&nbsp;&nbsp; OP_RETURN_252", link: "/opcodes/OP_RETURN_252.md" },
        { text: "<code>[ 253 ]</code>&nbsp;&nbsp; OP_RETURN_253", link: "/opcodes/OP_RETURN_253.md" },
        { text: "<code>[ 254 ]</code>&nbsp;&nbsp; OP_RETURN_254", link: "/opcodes/OP_RETURN_254.md" },
        { text: "🚧 255 OP_INVALIDOPCODE 🚧", link: "/opcodes/WIP.md" },
      ],
      
      "/script/": [
        { text: "Script Basics", link: "/script/script_basics.md"},
        { text: "Script Success and Failure", link: "/script/script.md" },
        { text: "ASM Representation", link: "/script/asm.md" },
        { text: "Push Operators", link: "/script/push.md" },
        { text: "Numbers in Script", link: "/script/numbers.md" },
      ]
    },
    
    socialLinks: [
      { icon: "github", link: "https://github.com/thunderbiscuit/opcode-explained" }
    ]
  }
})
